# Project information
site_name: Private Square's Documentation
site_description: 
site_author: 'Allan Tony Selvan'
site_url: 'https://docs.privatesquare.in'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'atselvan/atselvan.github.io'
repo_url: 'https://github.com/atselvan/atselvan.github.io'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Private Square'

pages:
- Home: 
  - Welcome: index.md
  - CICD: blog/cicd-fundamentals.md
  - Networking: blog/networking-fundamentals.md
  - Cloud Computing : blog/cloud-computing.md
  - Internet Of Things : blog/internet-of-things.md
  - IAAS, PAAS and SAAS: blog/understanding-iaas-paas-saas.md
- CICD:
  - Introduction: blog/cicd-fundamentals.md
  - Jenkins: 
      - Introduction: cicd/jenkins/index.md
- Docker:
  - Introduction : docker/index.md
  - Docker Compose: docker/docker-compose.md
  - Docker Machine: docker/docker-machine.md
  - Docker Networks: docker/docker-networks.md
  - Docker Secrets: docker/docker-secrets.md
- Golang:
  - Introduction: go/index.md
- AWS:
  - Introduction : aws/index.md
  - Cloud Computing : blog/cloud-computing.md
  - Global Infrastructure : aws/global-infrastructure.md
  - Services : 
    - Security, Identity and Compliance : aws/services/security-identity-compliance.md
    - Compute : aws/services/compute.md
    - Storage : aws/services/storage.md
    - Database : aws/services/database.md
    - Migration : aws/services/migration.md
    - Networking and Content Delivery : aws/services/networking-and-content-delivery.md
    - Developer Tools : aws/services/developer-tools.md
    - Management Tools : aws/services/management-tools.md
    - Machine Learning : aws/services/machine-learning.md
    - Analytics : aws/services/analytics.md
    - Mobile Services : aws/services/mobile-services.md
    - Application Integration : aws/services/application-integration.md
    - Customer Engagement : aws/services/customer-engagement.md
    - Business Productivity : aws/services/business-productivity.md
    - Desktop and App Streaming : aws/services/desktop-and-app-streaming.md
    - Internet Of Things : aws/services/internet-of-things.md
    - Game Development : aws/services/game-development.md

# Theme
theme: 
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: assets/images/logo-black.svg
  logo: assets/images/logo-white.svg
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extra Options
extra:
  search:
    language: 'en'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/atselvan'
    - type: 'github'
      link: 'https://github.com/atselvan'
    - type: 'bitbucket'
      link: 'https://bitbucket.org/privatesquare'
    - type: 'facebook'
      link: 'https://www.facebook.com/allantonyselvan'
    - type: 'twitter'
      link: 'https://twitter.com/allanselvan'
    - type: 'instagram'
      link: 'https://www.instagram.com/_atselvan'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde