# Project information
site_name: Private Square's Documentation
site_description: 
site_author: 'Allan Tony Selvan'
site_url: 'https://atselvan.github.io'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'atselvan/atselvan.github.io'
repo_url: 'https://github.com/atselvan/atselvan.github.io'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Private Square'

pages:
- Home: 
  - Welcome: index.md
  - CICD fundamentals: blog/cicd-fundamentals.md
  - Networking fundamentals: blog/networking-fundamentals.md
  - Understanding IAAS, PAAS and SAAS: blog/understanding-iaas-paas-saas.md
- Docker:
  - Home: docker/index.md
  - Docker compose: docker/docker-compose.md
  - Docker machine: docker/docker-machine.md
  - Docker networks: docker/docker-networks.md
  - Docker secrets: docker/docker-secrets.md
- AWS: 
  - Zones : aws/region-availabilityzones-edgezones.md

# Theme
theme: 
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: assets/images/logo-black.svg
  logo: assets/images/logo-white.svg
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extra Options
extra:
  search:
    language: 'en'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/atselvan'
    - type: 'github'
      link: 'https://github.com/atselvan'
    - type: 'bitbucket'
      link: 'https://bitbucket.org/privatesquare'
    - type: 'facebook'
      link: 'https://www.facebook.com/allantonyselvan'
    - type: 'twitter'
      link: 'https://twitter.com/allanselvan'
    - type: 'instagram'
      link: 'https://www.instagram.com/_atselvan'
  disqus: 'privatesquare'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde