# Project information
site_name: Private Square's Documentation
site_description: 
site_author: 'Allan Tony Selvan'
site_url: 'https://docs.privatesquare.in'

# Docs dir
docs_dir: './docs/'

# Repository
repo_name: 'atselvan/atselvan.github.io'
repo_url: 'https://github.com/atselvan/atselvan.github.io'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Private Square'

pages:
- Home: 
  - Welcome: index.md
  - CICD: blog/cicd-fundamentals.md
  - Networking: blog/networking-fundamentals.md
  - Host internet accessible website on your laptop: blog/host-internet-accessible-website-on-laptop.md
  - Cloud Computing : blog/cloud-computing.md
  - Raft Consesus Algorithm: blog/raft-consensus-algorithm.md
  - Containers and Container Orchestration: blog/container-orchestration.md
  - Container Orchestration Tools: blog/container-orchestration-tools.md
  - Internet Of Things : blog/internet-of-things.md
  - IAAS, PAAS and SAAS: blog/understanding-iaas-paas-saas.md
- Docker:
  - Introduction : docker/index.md
  - Docker Compose: docker/docker-compose.md
  - Docker Machine: docker/docker-machine.md
  - Docker Networks: docker/docker-networks.md
  - Docker Secrets: docker/docker-secrets.md
- Golang:
  - Introduction: golang/index.md
  - Http Request in Go: golang/http-request.md
  - Http Request via a Proxy: golang/http-request-proxy.md
  - String Functions: golang/string-functions.md
  - Slices in Go: golang/slices.md
  - Modify Go Usage flag: golang/modify-usage-flag.md
- Ansible:
  - Index : ansible/index.md
  - Ansible 101 : ansible/ansible101.md
- Jenkins:
  - Introduction: tools/jenkins/index.md
  - Access Control in Jenkins: tools/jenkins/access-control-rbac.md
  - Cloudbees Jenkins Analytics (CJA): tools/jenkins/analytics.md
  - Cloning a Jenkins Master instance: tools/jenkins/clone.md
  - Running Dynamic Jenkins slaves on AWS: tools/jenkins/jenkins-ec2-plugin.md
  - How does Jenkins decide where to run any give build: tools/jenkins/even-scheduler-plugin.md
- OpenLDAP:
  - Introduction: tools/openldap/index.md
  - Installation: tools/openldap/install.md
  - Configuration: tools/openldap/config.md
  - Server Error Codes: tools/openldap/ldap-server-error-codes.md
  - FAQ: tools/openldap/faq.md
- AWS:
  - Introduction : aws/index.md
  - Cloud Computing : blog/cloud-computing.md
  - Global Infrastructure : aws/global-infrastructure.md
  - Services : 
    - Security, Identity and Compliance : aws/services/security-identity-compliance.md
    - Compute : aws/services/compute.md
    - Storage : aws/services/storage.md
    - Networking and Content Delivery : aws/services/networking-and-content-delivery.md
    - Management Tools : aws/services/management-tools.md
    - Database : aws/services/database.md
    - Migration : aws/services/migration.md
    - Developer Tools : aws/services/developer-tools.md
    - Machine Learning : aws/services/machine-learning.md
    - Analytics : aws/services/analytics.md
    - Mobile Services : aws/services/mobile-services.md
    - Application Integration : aws/services/application-integration.md
    - Customer Engagement : aws/services/customer-engagement.md
    - Business Productivity : aws/services/business-productivity.md
    - Desktop and App Streaming : aws/services/desktop-and-app-streaming.md
    - Internet Of Things : aws/services/internet-of-things.md
    - Game Development : aws/services/game-development.md
  - AWS CLI on Mac : aws/awscli.md
# Theme
theme: 
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: assets/images/logo-black.svg
  logo: assets/images/logo-white.svg
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Extra Options
extra:
  search:
    language: 'en'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/atselvan'
    - type: 'github'
      link: 'https://github.com/atselvan'
    - type: 'bitbucket'
      link: 'https://bitbucket.org/privatesquare'
    - type: 'facebook'
      link: 'https://www.facebook.com/allantonyselvan'
    - type: 'twitter'
      link: 'https://twitter.com/allanselvan'
    - type: 'instagram'
      link: 'https://www.instagram.com/_atselvan'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde